name: Using Multiple Workflow

on: push

jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Library
          run: sudo apt-get install cowsay -y

        - name: Generate Ascii Artwork in CMD
          run: cowsay -f dragon "Hello Prateek" >> dragon.txt

        - name: Sleep for 30seconds
          run: sleep 30

    Test_job:
        needs: Build_job
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test file exists
          run: grep -i "Hello" dragon.txt

    Deployment_job:
        needs: [Test_job]
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploying
          run: echo deploying....