name: Workflow Filters and Activities

on:
    workflow_dispatch:
    push: 
        #branches-ignore: 
          #  - feature/*               #feature/addmusic
           # - test/**                   #featyure/test/home
        branches: 
            - main
            - '!feature/*'

    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this is a workflow/job/step executed for event type - ${{github.event_name}} 
